---
title: "hw2"
Author: "hw2765"
output: html_document
---

Problem1

```{r}
library(tidyverse)
getwd()
library(readxl)
```
```{r}
trashwheel = read_xlsx("./Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = "Mr. Trash Wheel", range = cell_cols("A:N")) %>%
  janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(
    sports_balls = round(sports_balls),
    sports_balls = as.integer(sports_balls)
  )
view(trashwheel)

P2017 = read_excel("./Trash-Wheel-Collection-Totals-8-6-19.xlsx",
  sheet = "2017 Precipitation",
  skip = 1, 
  ) %>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  mutate(year = 2017)  %>%
  relocate(year)
```


Problem 3

```{r}
library(tidyr)
polsmonth = read_csv(file = "./fivethirtyeight_datasets/pols-month.csv") %>%
  janitor::clean_names() %>%
  drop_na() %>%
  separate(mon, into = c("year", "month", "day"), sep = "-" ) %>%
  mutate(month = recode(month, `01` = "Jan", `02` = "Feb", `03` = "Mar", 
                        `04` = "Apr", `05` = "May", `06` = "Jun", 
                        `07` = "Jul", `08` = "Aug", `09` = "Sep", 
                        `10` = "Oct", `11` = "Nov", `12` = "Dec" )) %>%
  mutate(president = case_when(prez_gop == 1 ~ "gop", prez_dem == 1 ~ "dem")) %>%
  select(year, month, gov_gop, sen_gop, rep_gop, gov_dem, sen_dem, rep_dem, president)
view(polsmonth)

```

